version: "3.9"

services:
  db:
    image: postgres:14
    volumes:
      - db_storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: devuser
      DATABASE_PASSWORD: devpass
      DATABASE_NAME: devdb

volumes:
  db_storage:
